/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BankStatementToOfxRouteImport } from './routes/bank-statement-to-ofx'
import { Route as BankStatementToQifRouteImport } from './routes/bank-statement-to-qif'
import { Route as BankStatementToTallyRouteImport } from './routes/bank-statement-to-tally'
import { Route as ChaseBankStatementToExcelRouteImport } from './routes/chase-bank-statement-to-excel'
import { Route as ExportRouteImport } from './routes/export'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as IciciBankStatementToExcelRouteImport } from './routes/icici-bank-statement-to-excel'
import { Route as PreviewRouteImport } from './routes/preview'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as AccountBillingRouteImport } from './routes/account/billing'
import { Route as AccountHistoryRouteImport } from './routes/account/history'
import { Route as AccountSettingsRouteImport } from './routes/account/settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BankStatementToOfxRoute = BankStatementToOfxRouteImport.update({
  id: '/bank-statement-to-ofx',
  path: '/bank-statement-to-ofx',
  getParentRoute: () => rootRouteImport,
} as any)
const BankStatementToQifRoute = BankStatementToQifRouteImport.update({
  id: '/bank-statement-to-qif',
  path: '/bank-statement-to-qif',
  getParentRoute: () => rootRouteImport,
} as any)
const BankStatementToTallyRoute = BankStatementToTallyRouteImport.update({
  id: '/bank-statement-to-tally',
  path: '/bank-statement-to-tally',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaseBankStatementToExcelRoute =
  ChaseBankStatementToExcelRouteImport.update({
    id: '/chase-bank-statement-to-excel',
    path: '/chase-bank-statement-to-excel',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExportRoute = ExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IciciBankStatementToExcelRoute =
  IciciBankStatementToExcelRouteImport.update({
    id: '/icici-bank-statement-to-excel',
    path: '/icici-bank-statement-to-excel',
    getParentRoute: () => rootRouteImport,
  } as any)
const PreviewRoute = PreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountBillingRoute = AccountBillingRouteImport.update({
  id: '/account/billing',
  path: '/account/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountHistoryRoute = AccountHistoryRouteImport.update({
  id: '/account/history',
  path: '/account/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSettingsRoute = AccountSettingsRouteImport.update({
  id: '/account/settings',
  path: '/account/settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bank-statement-to-ofx': typeof BankStatementToOfxRoute
  '/bank-statement-to-qif': typeof BankStatementToQifRoute
  '/bank-statement-to-tally': typeof BankStatementToTallyRoute
  '/chase-bank-statement-to-excel': typeof ChaseBankStatementToExcelRoute
  '/export': typeof ExportRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/icici-bank-statement-to-excel': typeof IciciBankStatementToExcelRoute
  '/preview': typeof PreviewRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/upload': typeof UploadRoute
  '/account/billing': typeof AccountBillingRoute
  '/account/history': typeof AccountHistoryRoute
  '/account/settings': typeof AccountSettingsRoute
  '/account/': typeof AccountIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bank-statement-to-ofx': typeof BankStatementToOfxRoute
  '/bank-statement-to-qif': typeof BankStatementToQifRoute
  '/bank-statement-to-tally': typeof BankStatementToTallyRoute
  '/chase-bank-statement-to-excel': typeof ChaseBankStatementToExcelRoute
  '/export': typeof ExportRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/icici-bank-statement-to-excel': typeof IciciBankStatementToExcelRoute
  '/preview': typeof PreviewRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/upload': typeof UploadRoute
  '/account/billing': typeof AccountBillingRoute
  '/account/history': typeof AccountHistoryRoute
  '/account/settings': typeof AccountSettingsRoute
  '/account': typeof AccountIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bank-statement-to-ofx': typeof BankStatementToOfxRoute
  '/bank-statement-to-qif': typeof BankStatementToQifRoute
  '/bank-statement-to-tally': typeof BankStatementToTallyRoute
  '/chase-bank-statement-to-excel': typeof ChaseBankStatementToExcelRoute
  '/export': typeof ExportRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/icici-bank-statement-to-excel': typeof IciciBankStatementToExcelRoute
  '/preview': typeof PreviewRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/upload': typeof UploadRoute
  '/account/billing': typeof AccountBillingRoute
  '/account/history': typeof AccountHistoryRoute
  '/account/settings': typeof AccountSettingsRoute
  '/account/': typeof AccountIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bank-statement-to-ofx'
    | '/bank-statement-to-qif'
    | '/bank-statement-to-tally'
    | '/chase-bank-statement-to-excel'
    | '/export'
    | '/forgot-password'
    | '/icici-bank-statement-to-excel'
    | '/preview'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/upload'
    | '/account/billing'
    | '/account/history'
    | '/account/settings'
    | '/account/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bank-statement-to-ofx'
    | '/bank-statement-to-qif'
    | '/bank-statement-to-tally'
    | '/chase-bank-statement-to-excel'
    | '/export'
    | '/forgot-password'
    | '/icici-bank-statement-to-excel'
    | '/preview'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/upload'
    | '/account/billing'
    | '/account/history'
    | '/account/settings'
    | '/account'
  id:
    | '__root__'
    | '/'
    | '/bank-statement-to-ofx'
    | '/bank-statement-to-qif'
    | '/bank-statement-to-tally'
    | '/chase-bank-statement-to-excel'
    | '/export'
    | '/forgot-password'
    | '/icici-bank-statement-to-excel'
    | '/preview'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/upload'
    | '/account/billing'
    | '/account/history'
    | '/account/settings'
    | '/account/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BankStatementToOfxRoute: typeof BankStatementToOfxRoute
  BankStatementToQifRoute: typeof BankStatementToQifRoute
  BankStatementToTallyRoute: typeof BankStatementToTallyRoute
  ChaseBankStatementToExcelRoute: typeof ChaseBankStatementToExcelRoute
  ExportRoute: typeof ExportRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  IciciBankStatementToExcelRoute: typeof IciciBankStatementToExcelRoute
  PreviewRoute: typeof PreviewRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  UploadRoute: typeof UploadRoute
  AccountBillingRoute: typeof AccountBillingRoute
  AccountHistoryRoute: typeof AccountHistoryRoute
  AccountSettingsRoute: typeof AccountSettingsRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank-statement-to-ofx': {
      id: '/bank-statement-to-ofx'
      path: '/bank-statement-to-ofx'
      fullPath: '/bank-statement-to-ofx'
      preLoaderRoute: typeof BankStatementToOfxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank-statement-to-qif': {
      id: '/bank-statement-to-qif'
      path: '/bank-statement-to-qif'
      fullPath: '/bank-statement-to-qif'
      preLoaderRoute: typeof BankStatementToQifRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank-statement-to-tally': {
      id: '/bank-statement-to-tally'
      path: '/bank-statement-to-tally'
      fullPath: '/bank-statement-to-tally'
      preLoaderRoute: typeof BankStatementToTallyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chase-bank-statement-to-excel': {
      id: '/chase-bank-statement-to-excel'
      path: '/chase-bank-statement-to-excel'
      fullPath: '/chase-bank-statement-to-excel'
      preLoaderRoute: typeof ChaseBankStatementToExcelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export': {
      id: '/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof ExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/icici-bank-statement-to-excel': {
      id: '/icici-bank-statement-to-excel'
      path: '/icici-bank-statement-to-excel'
      fullPath: '/icici-bank-statement-to-excel'
      preLoaderRoute: typeof IciciBankStatementToExcelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/billing': {
      id: '/account/billing'
      path: '/account/billing'
      fullPath: '/account/billing'
      preLoaderRoute: typeof AccountBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/history': {
      id: '/account/history'
      path: '/account/history'
      fullPath: '/account/history'
      preLoaderRoute: typeof AccountHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/settings': {
      id: '/account/settings'
      path: '/account/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof AccountSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BankStatementToOfxRoute: BankStatementToOfxRoute,
  BankStatementToQifRoute: BankStatementToQifRoute,
  BankStatementToTallyRoute: BankStatementToTallyRoute,
  ChaseBankStatementToExcelRoute: ChaseBankStatementToExcelRoute,
  ExportRoute: ExportRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  IciciBankStatementToExcelRoute: IciciBankStatementToExcelRoute,
  PreviewRoute: PreviewRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  UploadRoute: UploadRoute,
  AccountBillingRoute: AccountBillingRoute,
  AccountHistoryRoute: AccountHistoryRoute,
  AccountSettingsRoute: AccountSettingsRoute,
  AccountIndexRoute: AccountIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
